config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  authenticate :user, lambda { |user| user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  concern :votable do
    member { post :vote }
  end

  concern :commentable do
    resources :comments, only: :create, shallow: true
  end

  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  resources :questions, except: [:edit], concerns: [:votable, :commentable] do
    resources :answers, shallow: true, only: [:create, :destroy, :update], concerns: [:votable, :commentable] do
      patch :accept, on: :member
    end

    resources :subscriptions, only: [:create, :destroy], shallow: true
  end

  resources :attachments, only: [:destroy]

  resources :awards, only: [:index]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index], controller: 'users' do
        get :me, on: :collection
      end

      resources :questions, except: [:new, :edit] do
        resources :answers, except: [:new, :edit], shallow: true
      end
    end
  end

  get 'search', to: 'search#show'

  root to: 'questions#index'
end

app/models/question.rb
class Question < ApplicationRecord
  include Linkable
  include Votable
  include Commentable

  after_create :create_subscription!

  has_many :answers, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_one :award, dependent: :destroy

  belongs_to :user

  has_many_attached :files

  accepts_nested_attributes_for :award, reject_if: :all_blank, allow_destroy: true

  validates :title, :body, presence: true

  default_scope { order(created_at: :desc) }

  private

  def create_subscription!
    subscriptions.create!(user: user)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :load_question, only: %i[show update destroy]

  authorize_resource

  def index
    @questions = Question.includes(:user, :answers).all
    render json: @questions, each_serializer: QuestionsSerializer
  end

  def show
    render json: @question
  end

  def create
    @question = current_resource_owner.questions.create!(question_params)
    render json: @question, status: :created
  end

  def update
    @question.update!(question_params)
  end

  def destroy
    @question.destroy!
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body,
                                     links_attributes: %i[name url])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: %i[index show]
  before_action :load_question, only: %i[show edit update destroy]
  before_action :load_subscription, only: :show
  after_action :publish_question, only: :create

  authorize_resource

  def index
    @questions = Question.all
  end

  def show
    @answer = Answer.new
    gon.question_user_id = @question.user_id
    gon.question_id = @question.id
  end

  def new
    @question = Question.new
    @question.build_award
  end

  def create
    @question = current_user.questions.build(question_params)

    if @question.save
      redirect_to @question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def update
    @question.update(question_params)
  end

  def destroy
    @question.destroy
    redirect_to questions_path, notice: 'Your question successfully deleted.'
  end

  private

  def load_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, files: [],
                                                    links_attributes: %i[id name url _destroy],
                                                    award_attributes: %i[name image])
  end

  def load_subscription
    @subscription = @question.subscriptions.find_by(user: current_user)
  end

  def publish_question
    return if @question.errors.any?

    ActionCable.server.broadcast(
      'questions_channel',
      ApplicationController.render(
        partial: 'questions/question',
        locals: { question: @question }
      )
    )
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_edit.html.slim
= form_with model: @question, class: 'hidden', html: {id: "edit-question-#{@question.id}"}  do |f|
  div.form-group.row
    = f.label :title, class:'col-sm-2 col-form-label'
    div.col-sm-10
      = f.text_field :title, placeholder: 'Edit Question Title', class: 'form-control'

  div.form-group.row
    = f.label :body, class:'col-sm-2 col-form-label'
    div.col-sm-10
      = f.text_area :body, placeholder: 'Edit Question Body', class: 'form-control'

  div.form-group.row
    div.custom-file
      = f.file_field :files, multiple: true, direct_upload: true, class: 'custom-file-input'
      = f.label :files, 'Choose Files', class: 'custom-file-label'

  div.form-group.row
    = render 'shared/link_form', f: f

  div.form-group.row
    div.col-sm-10
      = f.submit 'Save', class: 'btn btn-primary'

app/views/questions/_form.html.slim
p
  = render 'shared/errors', resource: @question

= form_with model: @question, local: true do |f|
  div.form-group.row
    = f.label :title, class:'col-sm-2 col-form-label'
    div.col-sm-10
      = f.text_field :title, class: 'form-control'

  div.form-group.row
    = f.label :body, class:'col-sm-2 col-form-label'
    div.col-sm-10
      = f.text_area :body, class: 'form-control'

  .files
    div.form-group.row
      div.custom-file
        = f.file_field :files, multiple: true, direct_upload: true, class: 'custom-file-input'
        = f.label :files,'Choose Files', class: 'custom-file-label', placeholder: 'Choose Files'

  .award
    div.form-group.row
        = render 'awards/form', f: f

  .links
    div.form-group.row
     = render 'shared/link_form', f: f

  div.form-group.row
    div.col-sm-10
      = f.submit 'Ask Question', class: 'btn btn-primary'

app/views/questions/_question.html.slim
div.card
  div.card-body
    h5.card-title
      p=link_to question.title, question_path(question)
    p.card-text= truncate(question.body, length: 200, escape: false)

app/views/questions/index.html.slim
= render 'shared/search_form'
h1 All Questions
div.card
  div.questions
    = render @questions

-if can?(:create, Question)
  p= link_to 'Ask Question', new_question_path

app/views/questions/new.html.slim
= render 'form'

app/views/questions/show.html.slim
- cache [@question, current_user]
  .question-errors

  .question class="question-#{@question.id}"
    div.card class="question-#{@question.id}"
      div.card-header
        h1= @question.title
      div.card-body
        .btn-group
          .w-30.p-2
            div.rating
              = render 'shared/rating', resource: @question
          .w-70.p-2
            p.body= @question.body
            -if @question.award
              div.award
                = render 'awards/award'
            div.files
              = render 'shared/files', resource: @question
            div.links
              = render 'shared/links', resource: @question

        p
        .btn-group
          -if can?(:update, @question)
            .col
              = link_to 'Delete', question_path(@question), method: :delete
            .col
              = link_to 'Edit', '#', class: 'edit-question-link', data: { question_id: @question.id }
          .col.subscription
              = render 'shared/subscriptions', resource: @question


    = render 'edit'
    .comments
      = render 'comments/comments', resource: @question
      -if can?(:create, Comment)
        = render 'comments/comment_form', resource: @question
      br
      br

    .comment-errors
      = render 'shared/errors', resource: @comment

  .answers
    -if @question.answers.present?
      h2= 'All Answers'
      = render @question.answers

  .answer-errors
    = render 'shared/errors', resource: @answer

  p
  .new_answer
    -if can?(:create, Answer)
      = link_to 'Add New Answer', '#', class: 'new-answer-link'
      = render 'answers/form'

app/views/questions/update.js.erb
var questionId = '<%= @question.id%>';
$('.question-errors').html('<%= render 'shared/errors', resource: @question%>');

<% if @question.errors.blank? %>
$('.question h1').text('<%= @question.title %>');
$('.question .card-body p.body').text('<%= @question.body %>');
$('.question div.files').html('<%= render 'shared/files', resource: @question%>');
$('.question div.links').html(`<%= render 'shared/links', resource: @question%>`);
$('form#edit-question-' + questionId).addClass('hidden');
$('.edit-question-link').show()
$('.container').prepend('<div class="alert alert-info">Your question successfully updated.</div>');
<% end %>