config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  authenticate :user, lambda { |user| user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  concern :votable do
    member { post :vote }
  end

  concern :commentable do
    resources :comments, only: :create, shallow: true
  end

  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  resources :questions, except: [:edit], concerns: [:votable, :commentable] do
    resources :answers, shallow: true, only: [:create, :destroy, :update], concerns: [:votable, :commentable] do
      patch :accept, on: :member
    end

    resources :subscriptions, only: [:create, :destroy], shallow: true
  end

  resources :attachments, only: [:destroy]

  resources :awards, only: [:index]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index], controller: 'users' do
        get :me, on: :collection
      end

      resources :questions, except: [:new, :edit] do
        resources :answers, except: [:new, :edit], shallow: true
      end
    end
  end

  get 'search', to: 'search#show'

  root to: 'questions#index'
end

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b= "#{resource.errors.count} error(s) detected: "
  ul
    -resource.errors.full_messages.each do |message|
      li= message

app/views/shared/_files.html.slim
-resource.files.each do |file|
  div class="file-#{file.id}"
    = link_to file.filename.to_s, url_for(file)
    -if can?(:destroy, file)
       = link_to 'x', attachment_path(file), class: 'delete-button', method: :delete, remote: true

app/views/shared/_flash.html.slim
-flash.each do |key, message|
  = content_tag :div, message.html_safe, class: "alert #{alert_class(key)}"

app/views/shared/_link_fields.html.slim
.nested-fields
  div[class='form-row']
    .col-md-6
        .field
          = f.text_field :name, class: 'form-control', placeholder: 'Link name'
    .col-md-6
      .field
        = f.text_field :url, class: 'form-control', placeholder: 'Link Url'
  = link_to_remove_association 'remove link', f

app/views/shared/_link_form.html.slim
#links
  = f.fields_for :links do |link|
    = render 'shared/link_fields', f: link
  .links
    = link_to_add_association 'add link', f, :links, partial: 'shared/link_fields'

app/views/shared/_links.html.slim
ul
  - resource.links.each do |link|
    li
      - if link.gist?
        code gist="#{link.url}.json" Loading gist
      - else
        = link_to link.name, link.url

app/views/shared/_nav.html.slim
nav class="navbar navbar-light bg-light"
  = link_to 'QnA', root_path, class: 'navbar-brand'

  span.navbar-text
    -if user_signed_in?
      span Welcome,
      b= current_user.email
      span |

      = link_to 'Log Out', destroy_user_session_path, method: :delete
    -else
      = link_to 'Sign In', new_user_session_path, method: :get
      span |
      = link_to 'Sign Up', new_user_registration_path, method: :get

app/views/shared/_rating.html.slim
.rating
  -if can?(:vote, resource)
    = button_to '▲', polymorphic_url(resource, action: :vote,
          voted: { value: 1 }), data: { type: :json }, class: 'btn text-success', color: :green, remote: true
  .circle = resource.rating
  -if can?(:vote, resource)
    = button_to '▼', polymorphic_url(resource, action: :vote,
          voted: { value: -1 }), data: { type: :json }, class: 'btn text-danger', remote: true

app/views/shared/_search_form.html.slim
.search
  = form_tag search_path, class: 'form-inline', method: :get do
    = search_field_tag :query, params[:query],  placeholder: 'Enter search term...', class: 'form-control'
    = select_tag :resource, options_for_select(SearchService::RESOURCES, params[:resource]), prompt: 'Everywhere', class: 'form-control mr-2'
    = submit_tag 'Search', class: 'btn btn-outline-secondary'
p

app/views/shared/_subscriptions.html.slim
-if can?(:create, Subscription)
  - if current_user.subscribed?(resource)
    = link_to 'Unsubscribe', subscription_path(@subscription), method: :delete, remote: true
  - else
    = link_to 'Subscribe', question_subscriptions_path(resource), method: :post, remote: true