config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  authenticate :user, lambda { |user| user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  concern :votable do
    member { post :vote }
  end

  concern :commentable do
    resources :comments, only: :create, shallow: true
  end

  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  resources :questions, except: [:edit], concerns: [:votable, :commentable] do
    resources :answers, shallow: true, only: [:create, :destroy, :update], concerns: [:votable, :commentable] do
      patch :accept, on: :member
    end

    resources :subscriptions, only: [:create, :destroy], shallow: true
  end

  resources :attachments, only: [:destroy]

  resources :awards, only: [:index]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index], controller: 'users' do
        get :me, on: :collection
      end

      resources :questions, except: [:new, :edit] do
        resources :answers, except: [:new, :edit], shallow: true
      end
    end
  end

  get 'search', to: 'search#show'

  root to: 'questions#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Linkable
  include Votable
  include Commentable

  after_commit :send_new_answer, on: :create

  belongs_to :question, touch: true
  belongs_to :user

  has_many_attached :files

  validates :body, presence: true
  validates :accepted, uniqueness: { scope: :question_id, accepted: true }, if: :accepted?

  default_scope { order('accepted DESC, created_at') }

  def accept!
    transaction do
      question.answers.update_all(accepted: false)

      update!(accepted: true)
      question.award&.update!(user: user)
    end
  end

  def send_new_answer
    NewAnswerJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted

  before_action :authenticate_user!
  before_action :load_question, only: %i[create]
  before_action :load_answer, only: %i[destroy update accept]
  after_action :publish_answer, only: :create

  authorize_resource

  def create
    @answer = @question.answers.create(answer_params.merge(user: current_user))
  end

  def update
    @question = @answer.question

    @answer.update(answer_params)
  end

  def destroy
    @answer.destroy
  end

  def accept
    @question = @answer.question

    @answer.accept!
  end

  private

  def load_question
    @question = Question.find(params[:question_id])
  end

  def load_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: %i[id name url _destroy])
  end

  def publish_answer
    return if @answer.errors.any?

    ActionCable.server.broadcast "/questions/#{@answer.question_id}/answers", @answer.to_json
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :load_question, only: %i[create index]
  before_action :load_answer, only: %i[show destroy update]

  authorize_resource

  def show
    render json: @answer
  end

  def index
    @answers = @question.answers.includes(:user)
    render json: @answers, each_serializer: AnswersSerializer
  end

  def create
    answer = @question.answers.create!(answer_params.merge(user: current_resource_owner))
    render json: answer, status: :created
  end

  def update
    @answer.update!(answer_params)
  end

  def destroy
    @answer.destroy!
  end

  private

  def load_answer
    @answer = Answer.find(params[:id])
  end

  def load_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require('answer').permit(:body, links_attributes: %i[name url])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- cache [answer, current_user]
  div.answer class= "answer-#{answer.id}"
    div.card class= "answer-#{answer.id}"
      div.card-body
        .btn-group
          .w-30.p-2
            div.rating
              = render 'shared/rating', resource: answer
          .w-70.p-2
            p.card-text= answer.body
            div.files
              = render 'shared/files', resource: answer
            div.links
              = render 'shared/links', resource: answer
        p
        .btn-group
          -if can?(:update, answer)
            .col
              = link_to 'Delete', answer_path(answer), method: :delete, remote: true
            .col
              = link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id }
          -if can?(:accept, answer) && !answer.accepted?
            .col-12
              = link_to 'Accept answer', accept_answer_path(answer), method: :patch, remote: true


    .comments
      = render 'comments/comments', resource: answer
      -if can?(:create, Comment)
        = render 'comments/comment_form', resource: answer
      br
      br

    = form_with model: answer, class: 'hidden', html: { id: "edit-answer-#{answer.id}" }  do |f|
      div.form-group.row
        = f.label :body, class:'col-sm-2 col-form-label'
        div.col-sm-10
          = f.text_area :body, placeholder: 'Edit answer', class: 'form-control'

      div.form-group.row
        div.custom-file
          = f.file_field :files, multiple: true, direct_upload: true, class: 'custom-file-input'
          = f.label :files, 'Choose Files', class: 'custom-file-label'

      div.form-group.row
        = render 'shared/link_form', f: f

      div.form-group.row
        div.col-sm-10
          = f.submit 'Save', class: 'btn btn-primary'

app/views/answers/_form.html.slim
= form_with model: [ @question, @answer ], class: 'hidden', html: {id: "new-answer-form"} do |f|
  div.card
    div.card-body
      div.form-group.row
        = f.text_area :body, placeholder: 'Your answer', class: 'form-control'

      div.form-group.row
        div.custom-file
          = f.file_field :files, multiple: true, direct_upload: true, class: 'custom-file-input'
          = f.label :files, placeholder: 'Choose Files', class: 'custom-file-label'

      div.form-group.row
        = render 'shared/link_form', f: f

      div.form-group.row
        div.col-sm-10
          = f.submit 'Answer the Question', class: 'btn btn-primary'

app/views/answers/accept.js.erb
$('.answers').html('<%= j render @question.answers %>');
$('.answers').prepend('<h2>All Answers</h2>');
$('.container').prepend('<div class="alert alert-info">Answer successfully accepted.</div>');

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer%>');

<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer %>');
  $('.new_answer #answer_body').val('');
  $('.container').prepend('<div class="alert alert-info">Your answer successfully created.</div>');
<% end %>

app/views/answers/destroy.js.erb
var answerId = '<%= @answer.id %>';

$('.answers .card').remove('.card.answer-' + answerId);
$('.container').prepend('<div class="alert alert-info">Your answer successfully deleted.</div>');

app/views/answers/update.js.erb
var answerId = '<%= @answer.id%>';
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer%>');

<% if !@answer.errors.present? %>
$('.answer-' + answerId + ' p.card-text').text('<%= @answer.body %>');
$('.answer-' + answerId + ' div.files').html('<%= render 'shared/files', resource: @answer%>');
$('.answer-' + answerId + ' div.links').html('<%= render 'shared/links', resource: @answer%>');
$('form#edit-answer-' + answerId).addClass('hidden');
$('.edit-answer-link').show()
$('.container').prepend('<div class="alert alert-info">Your answer successfully updated.</div>');
<% end %>